config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end
  #   collection do
  #     get :top
  #   end
  #   member do
  #     get :chef
  #   end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy chef]
  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  def chef
    @chef_name = @restaurant.chef_name
  end

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to @restaurant
  end

  def edit; end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBeyondCrud</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/_list.html.erb
<div id="restaurants">
  <% restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>

app/views/restaurants/_restaurant.html.erb
<h1>Restaurants</h1>

<%= render "list", restaurants: @restaurants %>

<%= link_to "New restaurant", new_restaurant_path %>

app/views/restaurants/chef.html.erb
<h1> <%= @restaurant.name %> Chef</h1>
<p><%= @chef_name %></p>
<%= link_to "Back to restaurant", restaurant_path(@restaurant) %>

app/views/restaurants/edit.html.erb
<h1> Vous éditez la page <%= @restaurant.name %></h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1> Vous êtes dans l'index </h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>Restaurant : <%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    <li>Address : <%= restaurant.address %></li>
    <li>Rating : <%= restaurant.rating %></li>
    <br>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

<%= link_to "Back", restaurants_path %>

app/views/restaurants/show.html.erb
<div class="container">
  <h1> Bienvenue chez <%= @restaurant.name %>! </h1>

  <p> Address : <%= @restaurant.address %></p>
  <p> Rating : <%= @restaurant.rating %></p>

  <%= link_to "Back", restaurants_path %>
  <%= link_to "Edit", edit_restaurant_path(@restaurant) %>
  <%= link_to "Delete",
    restaurant_path(@restaurant),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
</div>

<div class="container mt-5">
  <p><strong> Reviews </strong></p>
  <ul class='list-group'>
    <% @restaurant.reviews.each do |review| %>
      <li class='list-group-item'>
        <%= review.content %>
        <%= link_to "Delete", review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </li>
    <% end  %>
  </ul>
</div>

app/views/restaurants/top.html.erb
<h1> 5 stars resto</h1>

<%= render "restaurants/list", restaurants: @restaurants %>
<%= link_to "Back to all restaurants", restaurants_path %>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Reviews#new</h1>
  <p>Find me in app/views/reviews/new.html.erb</p>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end  %>
</div>